services:
  pg-docker:
    image: postgres
    container_name: dev-postgresql
    environment:
      POSTGRES_DB: e-shop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge