services:
  backend:
    container_name: api-app
    image: freitas022/e-shop
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://pg-docker:5432/e-shop
      DB_USERNAME: postgres
      DB_PASSWORD: password
    depends_on:
      - postgres
    networks:
      - e-shop
  postgres:
    container_name: postgres-sql
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  e-shop:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: