services:
  pg-docker:
    image: postgres:15-alpine
    container_name: dev-postgresql
    environment:
      DB_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge